### ISSUE TITLE
doesn't build on macOS

### ISSUE THREAD

**Issue by Asmod4n** [hone/mruby-docopt#6]
When trying to build on Darwin 15 it cannot find docopt_s.

I am using mruby/throw.h, so i have to disable cxx exceptions.

clang -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0

**Comment by toch** [comment]
Hi @Asmod4n, Thanks for reporting this.

If you disable cxx exceptions, I'm afraid you won't be able to compile mruby-docopt as docopt is a C++ lib.

Could you report your exact output please?

**Comment by Asmod4n** [comment]
build: [exec] cmake -G "Unix Makefiles"
-- Configuring done
-- Generating done
-- Build files have been written to: mruby/build/host/mrbgems/mruby-docopt/docopt
build: [exec] make
[ 33%] Built target docopt_o
[ 66%] Built target docopt_s
[100%] Built target docent
**snip**
AR    build/host/lib/libmruby_core.a 
LD    build/host/bin/mrbc 
ld: library not found for -ldocopt_s

**Comment by Asmod4n** [comment]
Have opened a issue at mruby/mruby for the cxx exceptions.

**Comment by Asmod4n** [comment]
Will close this until https://github.com/mruby/mruby/issues/3164 is resolved.
